project:
  name: vpc

tests:
  vpc-test:
    template: templates/vpc.yml
    regions:
      - "us-east-2"
    parameters:
      pJoeyIp: "100.100.100.100"
      pJoeyHomePsk: "totallybogus"
      pSsmInstanceProfile: $[taskcat_random-string]