AWSTemplateFormatVersion: 2010-09-09
Description: |
  Basic Test

Resources:
  TestS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: testtaskcatbucket12345
      VersioningConfiguration:
        Status: Enabled